[project]
name = "vocomorph"
version = "0.1.0"
description = "Neural Vocal Modulator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "absl-py==2.1.0",
    "audioread==3.0.1",
    "certifi==2024.12.14",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "contourpy==1.3.1",
    "cycler==0.12.1",
    "decorator==5.1.1",
    "einops==0.8.1",
    "encodec==0.1.1",
    "filelock==3.16.1",
    "fonttools==4.55.3",
    "fsspec==2024.12.0",
    "grpcio==1.71.0",
    "huggingface-hub==0.30.2",
    "idna==3.10",
    "jinja2==3.1.5",
    "joblib==1.4.2",
    "kiwisolver==1.4.8",
    "lazy-loader==0.4",
    "librosa==0.10.2.post1",
    "lightning-utilities==0.14.0",
    "llvmlite==0.43.0",
    "markdown==3.7",
    "markupsafe==3.0.2",
    "matplotlib==3.10.0",
    "mpmath==1.3.0",
    "msgpack==1.1.0",
    "mypy-extensions==1.0.0",
    "networkx==3.4.2",
    "numba==0.60.0",
    "numpy==2.0.2",
    "packaging==24.2",
    "pandas==2.2.3",
    "pathspec==0.12.1",
    "pillow==11.1.0",
    "platformdirs==4.3.6",
    "pooch==1.8.2",
    "protobuf==6.30.1",
    "pycparser==2.22",
    "pyloudnorm>=0.1.1",
    "pyparsing==3.2.1",
    "pytest>=8.4.1",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.1",
    "pyyaml==6.0.2",
    "requests==2.32.3",
    "scikit-learn==1.6.1",
    "scipy==1.15.1",
    "six==1.17.0",
    "soundfile==0.13.0",
    "soxr==0.5.0.post1",
    "sympy==1.13.1",
    "tensorboard==2.19.0",
    "tensorboard-data-server==0.7.2",
    "threadpoolctl==3.5.0",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "torcheval==0.0.7",
    "torchinfo==1.8.0",
    "torchmetrics==1.6.3",
    "tqdm==4.67.1",
    "typing-extensions==4.12.2",
    "tzdata==2025.1",
    "urllib3==2.3.0",
    "werkzeug==3.1.3",
]
